// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jondlbgouhsdedhdnwpx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvbmRsYmdvdWhzZGVkaGRud3B4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxODMyNTUsImV4cCI6MjA1Mzc1OTI1NX0.fmEpQxOe0Z76-sUd-OG8bQwQLE46DTm3uRrQpJjLvlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);